version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\BunBlog
before_build:
  - dotnet --version
  - dotnet restore BunBlog.sln
build_script:
  - dotnet build ./build/build.msbuild
after_build:
  - ps: Add-AppveyorTest -Name Test -Framework MSTest -FileName .\build\UnitTestReport.xml
test: off
deploy: off